Bug#14862 undefined reference to `isinf' on SOLARIS - strings/strtod.c  - Change the configure test looking for 'isinf' so the value returned from isinf is used. That avoids the call to isinf being optimized away.