WL#5825 Using C++ Standard Library with MySQL code post-push cleanup: the old workaround to avoid   undefined reference to `__pure_virtual' no longer works. The client library contains C++ code, and must be linked with g++